#!/bin/bash

e="t"
echo "1 - nano"
echo "2 - vi"
echo "3 - links"
echo "4 - exit"
while [[ true ]]
do
	read string
	case $string in
		"1")
			nano
			;;
		"2")
			vi
			;;
		"3")
			links
			;;
		"4")
			break
			;;
	esac
done
